박근우 - 상품 관련 API 추가
wecode-bootcamp-korea/36-1st-BIKINGS-backend pull request #5
Opened 2022-08-19 11:09 UTC by parklaus1078

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프론트엔드에서 상품 기본 정보(대표 사진, 상품명, 가격, 태그)를 GET 요청할 때 필요한 정보만 전송
- 상품 기본 정보 페이지에 유저가 접속했을 때 상품 기본 정보를 6개씩 나눠서 전송
- 프론트엔드에서 상품 상세 정보(상세 정보 소개 사진, 상품명, 가격, 태그)를 GET 요청할 때 필요한 정보만 전송
- 태그 조합으로 필터링하여 해당 태그를 가지고 있는 상품 기본 정보를 전송(필터링 창)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 기본 정보(페이지 별) 전송
- GET/products/covers/:page_num 요청으로 각 페이지에 출력할 상품 기본 정보들을 전송
- 페이지 당 상품 개수 offset을 6으로 설정하여 유저가 1 페이지에 접속 시, 1~6까지의 상품 ID를 가진 상품들의 기본 정보를 전송하고 2 페이지에 접속 시, 7~12까지의 상품 ID를 가진 상품들의 기본 정보를 전송하는 식으로 작동
- 요청한 페이지 수에 표시할 상품이 없다면 오류를 전송.

2. 상품 상세 정보 전송
- GET/products/details/:product_id 요청으로 해당 상품 ID를 가진 상품의 상세 정보들을 전송
- 요청한 ID를 보유한 상품이 존재하지 않을 시, 오류를 전송.

3. 태그 필터링
- GET/products 요청으로 request.body에 태그 배열을 받고, 해당 태그를 포함하고 있는 상품의 기본 정보들을 전송.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Mysql query 문을 조금 더 유동성 있고, 확장성 있게 사용할 수 있으면 소스의 양이 훨씬 줄어들 것.
- 
<br />

## :: 기타 질문 및 특이 사항
- query문으로만 태그 필터링이 가능한 방법이 있을까요?

2022-08-22 07:59 UTC, bigfanoftim requested changes
엔드포인트별로 PR을 분리해서 올려주세요!

이렇게 너무 많은 코드가 나열되어 있으면 어디서 어떻게 사용되는 코드인지 정확히 파악하기 어렵습니다.

2022-08-22 10:48 UTC, bigfanoftim requested changes

2022-08-22 10:48 UTC, bigfanoftim commented on routes/productRouter.js
> +router.get('/covers/:page_num', productController.getProductsCovers);
```JavaScript
// 이렇게 작성하면 product의 cover에 대한 정보를 불러오는 것처럼 보입니다.
:3000/products/covers

// 그냥 product 리스트를 받아오는 것이니 이렇게 작성하는 것이 더 좋아보입니다.
:3000/products
```
보통 `pagination`은 지금처럼 page number를 엔드포인트 경로에 고정시켜서 받는게 아니라 limit, offset을 `query parameters`로 전달받아서 SQL에서 LIMIT, OFFSET을 지정하여 필요한 만큼만 잘라서 주게 되고, SQL 조건에 맞는 모든 products rows 수를 보내줘 총 상품의 갯수도 파악할 수 있어야 합니다.

2022-08-23 03:19 UTC, bigfanoftim commented on routes/productRouter.js
> +router.get('/covers/:page_num', productController.getProductsCovers);
근우님 이전에 드린 리뷰에 이어 다시 말씀드리면 limit, offset은 query parameter로 받아주세요.

[참고 링크](https://ryan-han.com/post/translated/pathvariable_queryparam/)

2022-08-23 03:46 UTC, parklaus1078 commented on routes/productRouter.js
> +router.get('/covers/:page_num', productController.getProductsCovers);
앗 제가 이해를 잘못했네요. query parameter로 받도록 수정했습니다!

2022-08-23 06:35 UTC, bigfanoftim commented on routes/productRouter.js
> +router.get('/covers/:page_num', productController.getProductsCovers);
근우님! 해당 PR 라벨은 다시 `수정 요청`으로 변경했습니다! 수정해 보시고 모르는 거 있으시면 물어봐주세요~

2022-08-23 09:19 UTC, bigfanoftim approved these changes
LGTM 👍 
mysql 드라이버가 달라진 내용은 팀원에게 다시 한번 언급해 주세요!

2022-08-23 09:19 UTC, merged